### ISSUE TITLE
Virtual Montessori Materials not working

### ISSUE THREAD

**Issue by gme912** [Virtual-Montessori/montessori-tools#47]
The links on this site bring you to a page that say: 500 undefined. I am bringing awareness to this issue.

**Comment by mhornbacher** [comment]
Good afternoon @gme912

Could you please provide the specific url.

Also this project has sadly been neglected due to a host of factors and may be taken offline soon.

**Comment by gme912** [comment]
Hi!
it is this link: https://www.virtualmontessorimaterials.com/checkerboard

We use this site almost every day in our classroom, I would hate to see it
go offline!

Thanks!

Adam

**Comment by mhornbacher** [comment]
Good afternoon Adam,

My apologies for what seems to have been a misunderstanding. I work day-to-day with enterprise clients where *soon* is a 2-3 year time frame 😉 

For now this has been migrated to a personal server (as such the downtime) to reduce costs and (long term) improve uptime. This server runs several other non-profit sites. As long as bandwidth remains reasonable and no serious security flaws are found it will remain hosted there. Beyond that the project may need to begin to fund itself.

Regarding your issue. The link loads just fine now (post the migration) in Chrome, FireFox and Edge latest (supported browsers). Would you be able to share the browser you are using?

Also would you be able to ensure your browser cache is cleared (try opening in incognito/private) as you may have a bad file locally from during the migration.

Best Regards,
Menachem M. Hornbacher.
